name: "Create PR"
on: 
  push:
    branches: gh-pages

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        head: ${{ github.ref }}
        base: main
        title: 'Auto PR: ${{ github.actor }}'
