name: Auto PR on new branch

on:
  push:
    branches:
      - '*'
      
jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      
      - name: Set git user
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Merge new branch into main
          branch: ${{ github.head_ref }}
          base: main
          title: 'Auto PR: ${{ github.actor }}'
          body: 'New branch ${{ github.head_ref }} was created. Merging into main.'
          draft: false
