name: Update test branch

on:
  push:
    branches:
      - '*'

jobs:
  pull-main-into-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test branch
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git config pull.rebase false  # merge strategy

      - name: Pull main branch into test
        run: |
          git pull origin main --allow-unrelated-histories

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
