name: Push to gh-pages branch

on:
  push:
    branches:
      - '*'
jobs:
  copy_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - name: Push changes to gh-pages
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          # if [ "${{ github.ref }}" != "refs/heads/main" ]; then
          git checkout gh-pages
          git merge --allow-unrelated-histories main
          git push origin gh-pages
          # fi
