name: Push to test branch

on:
  push:
    branches:
      - '*'

jobs:
  copy_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes to test
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git checkout testz
          git merge --allow-unrelated-histories main
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git testz
