name: Sync multiple branches
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Merge main into test
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout test
          git pull
          git merge main --allow-unrelated-histories -m "Merge main into test"
          git push origin test

      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}
