name: Merge main into test

on:
  push:
    branches:
      - '*'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Add this line

      - name: Merge main
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git checkout main
          git pull
          git checkout test
          git merge main --allow-unrelated-histories
          git push
