name: Sync Branch with Main

on:
  push:
    branches:
      - '*'

jobs:
  sync_with_main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Push to Main if Branch Changed
      run: |
        current_branch=$(git branch --show-current)
        
        if [ "$current_branch" != "main" ]; then
          git push origin "$current_branch":main
        fi
