name: Sync multiple branches
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Merge main into test
        run: |
          git checkout test
          git pull
          git merge main --allow-unrelated-histories -m "Merge main into test"
          git push origin test
