name: Sync and PR on new branch

on:
  push:
    branches: test
    
jobs:
  sync_and_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Push to new branch
        run: |
          git checkout test
          git merge main
          git push origin test 
