name: Sync and PR on push to test branch

on:
  push:
    branches:
      - '*'

jobs:
  sync_and_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Merge and push to test branch
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git checkout test
          git merge main --allow-unrelated-histories
          git push origin test
