name: Merge main into test

on:
  push:
    branches:
      - '*'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge main
        run: |
          git config --global user.name "doxsuu"
          git config --global user.email "doxsuu@gmail.com"
          git checkout main
          git pull
          git checkout test
          git merge main --allow-unrelated-histories
          git push
